[project]
name = "ParallelProse"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Marcelo Hanones", email = "marcelohanones@gmail.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
parallelprose = "ParallelProse:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "ParallelProse"

[dependency-groups]
dev = [
    "ipykernel>=7.3.0",
]
